### ISSUE TITLE
Mod Menu broken implementation

### ISSUE THREAD

**Issue by itsdinkd** [Snownee/Nimble#13]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

latest

### Modloader version

latest

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'modmenu' provided by 'nimble'
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.2) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.12.12.jar:?]
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$0(ModMenu.java:71) ~[modmenu-3.0.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:67) ~[modmenu-3.0.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.12.12.jar:?]
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9) ~[notenoughcrashes-4.1.3+1.18.1-fabric.jar:?]
	at net.minecraft.client.MinecraftClient.redirect$hpf000$catchFabricInit(MinecraftClient:33478) ~[?:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:452) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:199) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: snownee.nimble.compat.modmenu.NimbleModMenuCompat
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.12.12.jar:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: snownee.nimble.compat.modmenu.NimbleModMenuCompat
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.12.12.jar:?]
	... 17 more

**Comment by sudofox** [comment]
i mean removing the ability to configure the mod entirely is _one_ way to do things...but still..

**Comment by Snownee** [comment]
@sudofox it's not removing. check the description on CurseForge
